#! /bin/sh

sxhkd &

pgrep -x sxhkd > /dev/null || sxhkd &
wname L3GD &

compton --config /home/qwerty/.config/compton/compton.conf &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         1
bspc config window_gap           0
bspc config focused_border_color    '#f0f000'

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config presel_feedback_color '#0ff340'

bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
bspc rule -a 'Pcmanfm' state=floating
#bspc rule -a 'polybar -rq ws' state=floating
bspc rule -a 'Tk' state=floating
#bspc rule -a '~/.config/polybar/launch.sh' state=floating 
bspc rule -a Screenkey manage=off
